FROM ghcr.io/isaacsancheza/images:python3.11

# install python packages
RUN pip --disable-pip-version-check --no-cache-dir install pyyaml chalice pydantic aws-cdk-lib cookiecutter chalice[cdkv2] pydantic-settings
