FROM ghcr.io/isaacsancheza/images:python3.8

# install python packages
RUN pip --disable-pip-version-check --no-cache-dir install pyyaml chalice pydantic aws-cdk-lib chalice[cdkv2] cookiecutter pydantic-settings
